### ISSUE TITLE
Prepare QuaCa publication

### ISSUE THREAD

**Issue by chegerland** [QuaCaTeam/quaca#60]
Let us prepare for our upcoming publication of QuaCa in JOSS. They have a [guide](https://joss.readthedocs.io/en/latest/submitting.html#submitting-a-paper-to-joss) on how to publish and these are the requirements:

- [x] 250 to 1000 words
- [x] A list of the authors of the software and their affiliations, using the correct format (see the example below).
- [x] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- [x] A Statement of Need section that clearly illustrates the research purpose of the software.
- [x] A list of key references, including to other software addressing related needs. Note that the references should include full names of venues, e.g., journals and conferences, not abbreviations only understood in the context of a specific discipline.
- [x] Mention (if applicable) a representative set of past or ongoing research projects using the software and recent scholarly publications enabled by it.
- [x] Acknowledgement of any financial support.

---
### Remaining tasks

**ToDos Paper:**
- [x] look over references in `paper/paper.bib` (remove file links)
- [x] add "Statement of Need"

**ToDos Repositories:**
- [x] improve read me @chegerland 
   - [x] expand test section (unit + integrated)
   - [x] explain apps Decay and Friction
   - [x] add badges
- [x] do tutorials again @chegerland @SiMaHer 
- [x] (optional) add coverage job and badge
